services:
    logged_in_redirection.listener.logged_in_user_listener:
        class: A5sys\LoggedInRedirectionBundle\Listener\LoggedInUserListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
            - "@router"
            - "@security.authorization_checker"
            - "%logged_in_redirection.route.route_name%"
            - "%logged_in_redirection.route.redirect_route_name%"
